spring:
  application:
    name: crm.validation
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/leadsdb
    username: leaduser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  cli:
    enabled: false